site: Stephen Laide
url: 
author: Stephen Laide
author:
  name: Stephen Laide
  email: stephenlaide@icloud.com
  url: 
  avatar: 
title: Stephen Laide
description: My personal website, blog and portfolio.
logo: 
image: 
contact:
  email: stephenlaide@icloud.com
  linkedin: https://linkedin.com/in/stephenlaide
  github: https://github.com/laideybug
  
permalink: pretty

baseurl:             ""

include:
  - _redirects
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  projects:
    output: true
    permalink: /projects/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"     
      
  - scope:
      path: "assets/images"
    values:
      image: true
